# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SecDbKeychainSerializedItemV7.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SecDbKeychainSerializedItemV7.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n#SecDbKeychainSerializedItemV7.proto\"\xaa\x02\n\x1dSecDbKeychainSerializedItemV7\x12\x1b\n\x13\x65ncryptedSecretData\x18\x01 \x02(\x0c\x12\x19\n\x11\x65ncryptedMetadata\x18\x02 \x02(\x0c\x12H\n\x08keyclass\x18\x03 \x02(\x0e\x32\'.SecDbKeychainSerializedItemV7.Keyclass:\rKEYCLASS_AKPU\"\x86\x01\n\x08Keyclass\x12\x0f\n\x0bKEYCLASS_AK\x10\x06\x12\x0f\n\x0bKEYCLASS_CK\x10\x07\x12\x0f\n\x0bKEYCLASS_DK\x10\x08\x12\x10\n\x0cKEYCLASS_AKU\x10\t\x12\x10\n\x0cKEYCLASS_CKU\x10\n\x12\x10\n\x0cKEYCLASS_DKU\x10\x0b\x12\x11\n\rKEYCLASS_AKPU\x10\x0c'
)



_SECDBKEYCHAINSERIALIZEDITEMV7_KEYCLASS = _descriptor.EnumDescriptor(
  name='Keyclass',
  full_name='SecDbKeychainSerializedItemV7.Keyclass',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='KEYCLASS_AK', index=0, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='KEYCLASS_CK', index=1, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='KEYCLASS_DK', index=2, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='KEYCLASS_AKU', index=3, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='KEYCLASS_CKU', index=4, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='KEYCLASS_DKU', index=5, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='KEYCLASS_AKPU', index=6, number=12,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=204,
  serialized_end=338,
)
_sym_db.RegisterEnumDescriptor(_SECDBKEYCHAINSERIALIZEDITEMV7_KEYCLASS)


_SECDBKEYCHAINSERIALIZEDITEMV7 = _descriptor.Descriptor(
  name='SecDbKeychainSerializedItemV7',
  full_name='SecDbKeychainSerializedItemV7',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='encryptedSecretData', full_name='SecDbKeychainSerializedItemV7.encryptedSecretData', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='encryptedMetadata', full_name='SecDbKeychainSerializedItemV7.encryptedMetadata', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='keyclass', full_name='SecDbKeychainSerializedItemV7.keyclass', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=12,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SECDBKEYCHAINSERIALIZEDITEMV7_KEYCLASS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=338,
)

_SECDBKEYCHAINSERIALIZEDITEMV7.fields_by_name['keyclass'].enum_type = _SECDBKEYCHAINSERIALIZEDITEMV7_KEYCLASS
_SECDBKEYCHAINSERIALIZEDITEMV7_KEYCLASS.containing_type = _SECDBKEYCHAINSERIALIZEDITEMV7
DESCRIPTOR.message_types_by_name['SecDbKeychainSerializedItemV7'] = _SECDBKEYCHAINSERIALIZEDITEMV7
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SecDbKeychainSerializedItemV7 = _reflection.GeneratedProtocolMessageType('SecDbKeychainSerializedItemV7', (_message.Message,), {
  'DESCRIPTOR' : _SECDBKEYCHAINSERIALIZEDITEMV7,
  '__module__' : 'SecDbKeychainSerializedItemV7_pb2'
  # @@protoc_insertion_point(class_scope:SecDbKeychainSerializedItemV7)
  })
_sym_db.RegisterMessage(SecDbKeychainSerializedItemV7)


# @@protoc_insertion_point(module_scope)
