# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SecDbKeychainSerializedMetadata.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SecDbKeychainSerializedMetadata.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n%SecDbKeychainSerializedMetadata.proto\"^\n\x1fSecDbKeychainSerializedMetadata\x12\x12\n\nciphertext\x18\x01 \x02(\x0c\x12\x12\n\nwrappedKey\x18\x02 \x02(\x0c\x12\x13\n\x0btamperCheck\x18\x03 \x02(\t'
)




_SECDBKEYCHAINSERIALIZEDMETADATA = _descriptor.Descriptor(
  name='SecDbKeychainSerializedMetadata',
  full_name='SecDbKeychainSerializedMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ciphertext', full_name='SecDbKeychainSerializedMetadata.ciphertext', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wrappedKey', full_name='SecDbKeychainSerializedMetadata.wrappedKey', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tamperCheck', full_name='SecDbKeychainSerializedMetadata.tamperCheck', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=135,
)

DESCRIPTOR.message_types_by_name['SecDbKeychainSerializedMetadata'] = _SECDBKEYCHAINSERIALIZEDMETADATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SecDbKeychainSerializedMetadata = _reflection.GeneratedProtocolMessageType('SecDbKeychainSerializedMetadata', (_message.Message,), {
  'DESCRIPTOR' : _SECDBKEYCHAINSERIALIZEDMETADATA,
  '__module__' : 'SecDbKeychainSerializedMetadata_pb2'
  # @@protoc_insertion_point(class_scope:SecDbKeychainSerializedMetadata)
  })
_sym_db.RegisterMessage(SecDbKeychainSerializedMetadata)


# @@protoc_insertion_point(module_scope)
