# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SecDbKeychainSerializedSecretData.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SecDbKeychainSerializedSecretData.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\'SecDbKeychainSerializedSecretData.proto\"\x83\x01\n!SecDbKeychainSerializedSecretData\x12\x12\n\nciphertext\x18\x01 \x02(\x0c\x12\x12\n\nwrappedKey\x18\x02 \x02(\x0c\x12\x13\n\x0btamperCheck\x18\x03 \x02(\t\x12!\n\x19SecDbBackupWrappedItemKey\x18\x04 \x01(\x0c'
)




_SECDBKEYCHAINSERIALIZEDSECRETDATA = _descriptor.Descriptor(
  name='SecDbKeychainSerializedSecretData',
  full_name='SecDbKeychainSerializedSecretData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ciphertext', full_name='SecDbKeychainSerializedSecretData.ciphertext', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wrappedKey', full_name='SecDbKeychainSerializedSecretData.wrappedKey', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tamperCheck', full_name='SecDbKeychainSerializedSecretData.tamperCheck', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='SecDbBackupWrappedItemKey', full_name='SecDbKeychainSerializedSecretData.SecDbBackupWrappedItemKey', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=175,
)

DESCRIPTOR.message_types_by_name['SecDbKeychainSerializedSecretData'] = _SECDBKEYCHAINSERIALIZEDSECRETDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SecDbKeychainSerializedSecretData = _reflection.GeneratedProtocolMessageType('SecDbKeychainSerializedSecretData', (_message.Message,), {
  'DESCRIPTOR' : _SECDBKEYCHAINSERIALIZEDSECRETDATA,
  '__module__' : 'SecDbKeychainSerializedSecretData_pb2'
  # @@protoc_insertion_point(class_scope:SecDbKeychainSerializedSecretData)
  })
_sym_db.RegisterMessage(SecDbKeychainSerializedSecretData)


# @@protoc_insertion_point(module_scope)
